stages:
  - deploy

pages:
  image: node:10.15.3
  only:
    - master
  stage: deploy
  tags:
    - misakey_docker
  script:
    - yarn install
    - yarn build
    - mv public public_src
    - cp -r build public
  artifacts:
    paths:
      - public
